export LD_LIBRARY_PATH=/data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/bcftools/lib/x86_64-linux-gnu
/data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/bcftools/bcftools norm -f /data/fulongfei/database/ref/hg19/hg19.fasta -m - -c w /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/IonXpress_017/TSVC_variants.vcf >/data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.vcf

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/Split_MNP.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.vcf >/data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.MNP.xls

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/Check_Dup_Vars_In_bcfnorm_splitMNP_vcf.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.Dup.Vars.xls

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/Remove_Dup_Vars_From_bcfnorm_splitMNP_vcf.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.Dup.Vars.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.vcf

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/scripts/filter_bcfnorm_vcf.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.pass_gt_filter.vcf

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/Check_TVC_Flow_Problem.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.Flow.Problem.txt

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/scripts/Stat_Sensitivity.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.pass_gt_filter.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/indel/YH-indel.vcf IonXpress_017 /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.Sensitivity.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.Sens_PPV_Summary.xls

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/scripts/Stat_PPV.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.pass_gt_filter.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/YH_info/YH.bed /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/indel/YH-indel.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.PPV.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.Sens_PPV_Summary.xls

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/scripts/Check_Sens_TVC_Detail.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.Sensitivity.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TVC.Info.Sens.xls

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/scripts/Check_PPV_TVC_Detail.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.PPV.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TVC.Info.PPV.xls

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/scripts/HS_InDel_Depth_Summary.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TVC.Info.Sens.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.HS.InDel.Depth.Summary.xls

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/scripts/HS_InDel_NoCall_Reason_Summary.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TVC.Info.Sens.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.HS.InDel.NoCall.Reason.Summary.xls

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/scripts/Stat_SNV_Sens_PPV/cal_snv_sens_ppv.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/YH_info/YH.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.pass_gt_filter.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/YH_info/YH.bed /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.snv.sens.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.snv.ppv.xls >/data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.snv.sens.ppv.summary.xls

# get final vcf for /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.pass_gt_filter.vcf file
perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/Modify_Chr_Plus_Qual.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.bcfnorm.splitMNP.rmdup.pass_gt_filter.vcf /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.TSVC_variants.final.vcf

perl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/IonAmpliSeqExome_ZJY/Summary_Results.pl /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.Sens_PPV_Summary.xls /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.snv.sens.ppv.summary.xls IonXpress_017 /data/fulongfei/git_repo/AmpliSeqExome_Sens_PPV_Plugin/test/variantCaller58_out.2011/Analysis/IonXpress_017/IonXpress_017.InDel.SNV.Sens.PPV.txt
